// Generated by gencpp from file move_arm_joints/move_and_confirm.msg
// DO NOT EDIT!


#ifndef MOVE_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRM_H
#define MOVE_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRM_H

#include <ros/service_traits.h>


#include <move_arm_joints/move_and_confirmRequest.h>
#include <move_arm_joints/move_and_confirmResponse.h>


namespace move_arm_joints
{

struct move_and_confirm
{

typedef move_and_confirmRequest Request;
typedef move_and_confirmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_and_confirm
} // namespace move_arm_joints


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_arm_joints::move_and_confirm > {
  static const char* value()
  {
    return "fee37082f61685d393bcb188db5d451f";
  }

  static const char* value(const ::move_arm_joints::move_and_confirm&) { return value(); }
};

template<>
struct DataType< ::move_arm_joints::move_and_confirm > {
  static const char* value()
  {
    return "move_arm_joints/move_and_confirm";
  }

  static const char* value(const ::move_arm_joints::move_and_confirm&) { return value(); }
};


// service_traits::MD5Sum< ::move_arm_joints::move_and_confirmRequest> should match
// service_traits::MD5Sum< ::move_arm_joints::move_and_confirm >
template<>
struct MD5Sum< ::move_arm_joints::move_and_confirmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_arm_joints::move_and_confirm >::value();
  }
  static const char* value(const ::move_arm_joints::move_and_confirmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_arm_joints::move_and_confirmRequest> should match
// service_traits::DataType< ::move_arm_joints::move_and_confirm >
template<>
struct DataType< ::move_arm_joints::move_and_confirmRequest>
{
  static const char* value()
  {
    return DataType< ::move_arm_joints::move_and_confirm >::value();
  }
  static const char* value(const ::move_arm_joints::move_and_confirmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_arm_joints::move_and_confirmResponse> should match
// service_traits::MD5Sum< ::move_arm_joints::move_and_confirm >
template<>
struct MD5Sum< ::move_arm_joints::move_and_confirmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_arm_joints::move_and_confirm >::value();
  }
  static const char* value(const ::move_arm_joints::move_and_confirmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_arm_joints::move_and_confirmResponse> should match
// service_traits::DataType< ::move_arm_joints::move_and_confirm >
template<>
struct DataType< ::move_arm_joints::move_and_confirmResponse>
{
  static const char* value()
  {
    return DataType< ::move_arm_joints::move_and_confirm >::value();
  }
  static const char* value(const ::move_arm_joints::move_and_confirmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRM_H
