// Generated by gencpp from file move_arm_joints/move_and_confirmResponse.msg
// DO NOT EDIT!


#ifndef MOVE_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRMRESPONSE_H
#define MOVE_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_arm_joints
{
template <class ContainerAllocator>
struct move_and_confirmResponse_
{
  typedef move_and_confirmResponse_<ContainerAllocator> Type;

  move_and_confirmResponse_()
    : confirm(0.0)  {
    }
  move_and_confirmResponse_(const ContainerAllocator& _alloc)
    : confirm(0.0)  {
  (void)_alloc;
    }



   typedef double _confirm_type;
  _confirm_type confirm;





  typedef boost::shared_ptr< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> const> ConstPtr;

}; // struct move_and_confirmResponse_

typedef ::move_arm_joints::move_and_confirmResponse_<std::allocator<void> > move_and_confirmResponse;

typedef boost::shared_ptr< ::move_arm_joints::move_and_confirmResponse > move_and_confirmResponsePtr;
typedef boost::shared_ptr< ::move_arm_joints::move_and_confirmResponse const> move_and_confirmResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator1> & lhs, const ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator2> & rhs)
{
  return lhs.confirm == rhs.confirm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator1> & lhs, const ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_arm_joints

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96898f38d1c4d4e2071b6fdfb561591f";
  }

  static const char* value(const ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96898f38d1c4d4e2ULL;
  static const uint64_t static_value2 = 0x071b6fdfb561591fULL;
};

template<class ContainerAllocator>
struct DataType< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_arm_joints/move_and_confirmResponse";
  }

  static const char* value(const ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 confirm\n"
"\n"
;
  }

  static const char* value(const ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.confirm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_and_confirmResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_arm_joints::move_and_confirmResponse_<ContainerAllocator>& v)
  {
    s << indent << "confirm: ";
    Printer<double>::stream(s, indent + "  ", v.confirm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRMRESPONSE_H
